
name: gecko
channels:
  - conda-forge
dependencies:
  - optuna
  - python=3.8
  - numpy
  - seaborn
  - scipy
  - properscoring
  - matplotlib
  - xarray
  - netcdf4
  - pyyaml
  - tqdm
  - dask
  - pandas
  - scikit-learn
  - pytest
  - jupyter
  - jupyterlab
  - jupyter_server
  - dask
  - distributed
  - pip
  - s3fs
  - pyarrow
  - flake8
  - pip:
    - tensorflow
    - torch
    - captum
    - shap
    - pyDOE
    - keras-self-attention
    - git+https://github.com/NCAR/echo-opt.git
    - .
