species: 'dodecane'
dir_path: '/glade/p/cisl/aiml/gecko/ML2019_dodecane_postproc/'
summary_file: 'C02000_Exp_List_ML2019_dodecane_v1_LatinHyperCube.csv'
aggregate_bins: True
save_models: True
scaler_type: "MinMaxScaler"
output_path: '/glade/work/cbecker/gecko-ml/save_out/'
x_scaler: 'dodecane_x.scaler'
y_scaler: 'dodecane_y.scaler'
bin_prefix: ['Gas [ug/m3]', 'Aerosol [ug_m3]']
min_exp: 0
max_exp: 1999
seq_length: 5
num_exps: 100
input_vars: [
    'Time [s]',
    'Precursor [ug/m3]',
    'Gas [ug/m3]',
    'Aerosol [ug_m3]',
    'temperature (K)',
    'solar zenith angle (degree)',
    'pre-existing aerosols (ug/m3)',
    'o3 (ppb)',
    'nox (ppb)',
    'oh (10^6 molec/cm3)',
    'id']
output_vars: [
    'Time [s]',
    'Precursor [ug/m3]',
    'Gas [ug/m3]',
    'Aerosol [ug_m3]',
    'id']

model_configurations:
  single_ts_models:
    dnn_1:
      hidden_layers: 1
      hidden_neurons: 4
      activation: "relu"
      output_activation: "linear"
      optimizer: "adam"
      loss: "mse"
      lr: 0.001
      batch_size: 1024
      use_noise: False
      noise_sd: 0.01
      epochs: 1
      use_dropout: False
      dropout_alpha: 0.1
      l2_weight: 0.01
      sgd_momentum: 0.9
      adam_beta_1: 0.9
      adam_beta_2: 0.999
      decay: 0
      verbose:  0
      classifier: False

  multi_ts_models:
    lstm_1:
      hidden_layers: 1
      hidden_neurons: 100
      activation: "tanh"
      output_activation: "tanh"
      optimizer: "adam"
      loss: "mse"
      lr: 0.001
      batch_size: 1024
      use_noise: False
      noise_sd: 0.01
      epochs: 10
      use_dropout: False
      dropout_alpha: 0.1
      l2_weight: 0.01
      sgd_momentum: 0.9
      adam_beta_1: 0.9
      adam_beta_2: 0.999
      decay: 0
      verbose: 1
      classifier: False

