species: 'dodecane'
dir_path: '/glade/p/cisl/aiml/gecko/ML2019_dodecane_postproc/'
summary_file: 'C02000_Exp_List_ML2019_dodecane_v1_LatinHyperCube.csv'
aggregate_bins: True
save_fortran: False
output_path: '~/'
bin_prefix: ['Gas [ug/m3]', 'Aerosol [ug_m3]']
min_exp: 0
max_exp: 1999
input_vars: [
    'Precursor [ug/m3]',
    'Gas [ug/m3]',
    'Aerosol [ug_m3]',
    'temperature (K)',
    'solar zenith angle (degree)',
    'pre-existing aerosols (ug/m3)',
    'o3 (ppb)',
    'nox (ppb)',
    'oh (10^6 molec/cm3)',
    'id']
output_vars: [
    'Precursor [ug/m3]',
    'Gas [ug/m3]',
    'Aerosol [ug_m3]',
    'id']