species: 'apin_O3'
dir_path: '/glade/p/cisl/aiml/gecko/partition_data/'
# dir_path: 'AWS:ncar-aiml-data-commons/gecko/' #use prefix 'AWS:' if path is AWS bucket
output_path: '/glade/work/schreck/repos/GECKO_OPT/dev/gecko-ml/results' #'/home/schreck/gecko_apin_rnn_agg_runs'
aggregate_bins: True
ensemble_members: 1 # set to 1 for a single run
scaler_type: "StandardScaler"
bin_prefix: ['Gas [ug/m3]', 'Aerosol [ug_m3]']
box_val_exps: 'all'
random_seed: 8886
input_vars: [
    'Precursor [ug/m3]',
    'Gas [ug/m3]',
    'Aerosol [ug_m3]',
    'temperature (K)',
    'solar zenith angle (degree)',
    'pre-existing aerosols (ug/m3)',
    'o3 (ppb)',
    'nox (ppb)',
    'oh (10^6 molec/cm3)']
output_vars: [
    'Precursor [ug/m3]',
    'Gas [ug/m3]',
    'Aerosol [ug_m3]']
log_trans_cols: ['Precursor [ug/m3]']
tendency_cols: []

model_configurations:
  RNN:
    GRU_1:
      hidden_size: 1850
      n_layers: 1
      lr: 2.4744313047838478e-05
      l2_weight: 1.1707655725204669e-08
      rnn_dropout: 0.4150365920866731
      hidden_weight: 1.8968990752892942
      batch_size: 767
      epochs: 250
      verbose: True
      lr_patience: 2
      stopping_patience: 7
      member: 0
      precursor_weight: 0.805104251214678
      gas_weight: 0.6214533134914141
      aero_weight: 0.8942207225531631
      validation_starting_times: [0, 10, 50, 100, 200, 500, 1000]
        
pbs:
  kernel: "ncar_pylib /glade/work/$USER/py37"
  bash: ["module load ncarenv/1.3 gnu/8.3.0 openmpi/3.1.4 python/3.7.5 cuda cudnn"]
  batch:
    N: "apin-gru"
    l: ["select=1:ncpus=8:ngpus=1:mem=128GB", "walltime=12:00:00", "gpu_type=v100"]
    A: "NAML0001"
    q: "casper"
    o: "/home/schreck/gecko_apin_rnn_agg_runs/out"
    e: "/home/schreck/gecko_apin_rnn_agg_runs/err"

