species: 'dodecane'
dir_path: '/glade/p/cisl/aiml/gecko/ML2019_dodecane_postproc/'
summary_file: 'C02000_Exp_List_ML2019_dodecane_v1_LatinHyperCube.csv'
aggregate_bins: False
save_fortran: False
output_path: '~/'
bin_prefix: ['Gas [ug/m3]', 'Aerosol [ug_m3]']
min_exp: 0
max_exp: 1999
input_vars: 
    ['Precursor [ug/m3]',
    'Gas [ug/m3] Bin01: lg(C*) = -6.5',
    'Gas [ug/m3] Bin02: lg(C*) = -5.5',
    'Gas [ug/m3] Bin03: lg(C*) = -4.5',
    'Gas [ug/m3] Bin04: lg(C*) = -3.5',
    'Gas [ug/m3] Bin05: lg(C*) = -2.5',
    'Gas [ug/m3] Bin06: lg(C*) = -1.5',
    'Gas [ug/m3] Bin07: lg(C*) = -0.5',
    'Gas [ug/m3] Bin08: lg(C*) =  0.5',
    'Gas [ug/m3] Bin09: lg(C*) =  1.5',
    'Gas [ug/m3] Bin10: lg(C*) =  2.5',
    'Gas [ug/m3] Bin11: lg(C*) =  3.5',
    'Gas [ug/m3] Bin12: lg(C*) =  4.5',
    'Gas [ug/m3] Bin13: lg(C*) =  5.5',
    'Gas [ug/m3] Bin14: lg(C*) =  6.5',
    'Aerosol [ug_m3] Bin01: lg(C*) = -6.5',
    'Aerosol [ug_m3] Bin02: lg(C*) = -5.5',
    'Aerosol [ug_m3] Bin03: lg(C*) = -4.5',
    'Aerosol [ug_m3] Bin04: lg(C*) = -3.5',
    'Aerosol [ug_m3] Bin05: lg(C*) = -2.5',
    'Aerosol [ug_m3] Bin06: lg(C*) = -1.5',
    'Aerosol [ug_m3] Bin07: lg(C*) = -0.5',
    'Aerosol [ug_m3] Bin08: lg(C*) =  0.5',
    'Aerosol [ug_m3] Bin09: lg(C*) =  1.5',
    'Aerosol [ug_m3] Bin10: lg(C*) =  2.5',
    'Aerosol [ug_m3] Bin11: lg(C*) =  3.5',
    'Aerosol [ug_m3] Bin12: lg(C*) =  4.5',
    'Aerosol [ug_m3] Bin13: lg(C*) =  5.5',
    'Aerosol [ug_m3] Bin14: lg(C*) =  6.5',
    'temperature (K)',
    'solar zenith angle (degree)',
    'pre-existing aerosols (ug/m3)',
    'o3 (ppb)',
    'nox (ppb)',
    'oh (10^6 molec/cm3)',
    'id']
output_vars:  
    ['Precursor [ug/m3]',
    'Gas [ug/m3] Bin01: lg(C*) = -6.5',
    'Gas [ug/m3] Bin02: lg(C*) = -5.5',
    'Gas [ug/m3] Bin03: lg(C*) = -4.5',
    'Gas [ug/m3] Bin04: lg(C*) = -3.5',
    'Gas [ug/m3] Bin05: lg(C*) = -2.5',
    'Gas [ug/m3] Bin06: lg(C*) = -1.5',
    'Gas [ug/m3] Bin07: lg(C*) = -0.5',
    'Gas [ug/m3] Bin08: lg(C*) =  0.5',
    'Gas [ug/m3] Bin09: lg(C*) =  1.5',
    'Gas [ug/m3] Bin10: lg(C*) =  2.5',
    'Gas [ug/m3] Bin11: lg(C*) =  3.5',
    'Gas [ug/m3] Bin12: lg(C*) =  4.5',
    'Gas [ug/m3] Bin13: lg(C*) =  5.5',
    'Gas [ug/m3] Bin14: lg(C*) =  6.5',
    'Aerosol [ug_m3] Bin01: lg(C*) = -6.5',
    'Aerosol [ug_m3] Bin02: lg(C*) = -5.5',
    'Aerosol [ug_m3] Bin03: lg(C*) = -4.5',
    'Aerosol [ug_m3] Bin04: lg(C*) = -3.5',
    'Aerosol [ug_m3] Bin05: lg(C*) = -2.5',
    'Aerosol [ug_m3] Bin06: lg(C*) = -1.5',
    'Aerosol [ug_m3] Bin07: lg(C*) = -0.5',
    'Aerosol [ug_m3] Bin08: lg(C*) =  0.5',
    'Aerosol [ug_m3] Bin09: lg(C*) =  1.5',
    'Aerosol [ug_m3] Bin10: lg(C*) =  2.5',
    'Aerosol [ug_m3] Bin11: lg(C*) =  3.5',
    'Aerosol [ug_m3] Bin12: lg(C*) =  4.5',
    'Aerosol [ug_m3] Bin13: lg(C*) =  5.5',
    'Aerosol [ug_m3] Bin14: lg(C*) =  6.5',
    'id']