species: 'dodecane'
dir_path: '/glade/p/cisl/aiml/gecko/partition_data/'
# dir_path: 'AWS:ncar-aiml-data-commons/gecko/' #use prefix 'AWS:' if path is AWS bucket
output_path: '/home/cbecker/gecko_dodecane_binned_runs'
aggregate_bins: False
ensemble_members: 1 # set to 1 for a single run
scaler_type: "StandardScaler"
bin_prefix: [ 'Gas [ug/m3]', 'Aerosol [ug_m3]' ]
box_val_exps: 'all'
random_seed: 8886
input_vars:
    ['Precursor [ug/m3]',
    'Gas [ug/m3] Bin01: lg(C*) = -6.5',
    'Gas [ug/m3] Bin02: lg(C*) = -5.5',
    'Gas [ug/m3] Bin03: lg(C*) = -4.5',
    'Gas [ug/m3] Bin04: lg(C*) = -3.5',
    'Gas [ug/m3] Bin05: lg(C*) = -2.5',
    'Gas [ug/m3] Bin06: lg(C*) = -1.5',
    'Gas [ug/m3] Bin07: lg(C*) = -0.5',
    'Gas [ug/m3] Bin08: lg(C*) =  0.5',
    'Gas [ug/m3] Bin09: lg(C*) =  1.5',
    'Gas [ug/m3] Bin10: lg(C*) =  2.5',
    'Gas [ug/m3] Bin11: lg(C*) =  3.5',
    'Gas [ug/m3] Bin12: lg(C*) =  4.5',
    'Gas [ug/m3] Bin13: lg(C*) =  5.5',
    'Gas [ug/m3] Bin14: lg(C*) =  6.5',
    'Aerosol [ug_m3] Bin01: lg(C*) = -6.5',
    'Aerosol [ug_m3] Bin02: lg(C*) = -5.5',
    'Aerosol [ug_m3] Bin03: lg(C*) = -4.5',
    'Aerosol [ug_m3] Bin04: lg(C*) = -3.5',
    'Aerosol [ug_m3] Bin05: lg(C*) = -2.5',
    'Aerosol [ug_m3] Bin06: lg(C*) = -1.5',
    'Aerosol [ug_m3] Bin07: lg(C*) = -0.5',
    'Aerosol [ug_m3] Bin08: lg(C*) =  0.5',
    'Aerosol [ug_m3] Bin09: lg(C*) =  1.5',
    'Aerosol [ug_m3] Bin10: lg(C*) =  2.5',
    'Aerosol [ug_m3] Bin11: lg(C*) =  3.5',
    'Aerosol [ug_m3] Bin12: lg(C*) =  4.5',
    'Aerosol [ug_m3] Bin13: lg(C*) =  5.5',
    'Aerosol [ug_m3] Bin14: lg(C*) =  6.5',
    'temperature (K)',
    'solar zenith angle (degree)',
    'pre-existing aerosols (ug/m3)',
    'o3 (ppb)',
    'nox (ppb)',
    'oh (10^6 molec/cm3)']
output_vars:
    ['Gas [ug/m3] Bin01: lg(C*) = -6.5',
    'Gas [ug/m3] Bin02: lg(C*) = -5.5',
    'Gas [ug/m3] Bin03: lg(C*) = -4.5',
    'Gas [ug/m3] Bin04: lg(C*) = -3.5',
    'Gas [ug/m3] Bin05: lg(C*) = -2.5',
    'Gas [ug/m3] Bin06: lg(C*) = -1.5',
    'Gas [ug/m3] Bin07: lg(C*) = -0.5',
    'Gas [ug/m3] Bin08: lg(C*) =  0.5',
    'Gas [ug/m3] Bin09: lg(C*) =  1.5',
    'Gas [ug/m3] Bin10: lg(C*) =  2.5',
    'Gas [ug/m3] Bin11: lg(C*) =  3.5',
    'Gas [ug/m3] Bin12: lg(C*) =  4.5',
    'Gas [ug/m3] Bin13: lg(C*) =  5.5',
    'Gas [ug/m3] Bin14: lg(C*) =  6.5',
    'Aerosol [ug_m3] Bin01: lg(C*) = -6.5',
    'Aerosol [ug_m3] Bin02: lg(C*) = -5.5',
    'Aerosol [ug_m3] Bin03: lg(C*) = -4.5',
    'Aerosol [ug_m3] Bin04: lg(C*) = -3.5',
    'Aerosol [ug_m3] Bin05: lg(C*) = -2.5',
    'Aerosol [ug_m3] Bin06: lg(C*) = -1.5',
    'Aerosol [ug_m3] Bin07: lg(C*) = -0.5',
    'Aerosol [ug_m3] Bin08: lg(C*) =  0.5',
    'Aerosol [ug_m3] Bin09: lg(C*) =  1.5',
    'Aerosol [ug_m3] Bin10: lg(C*) =  2.5',
    'Aerosol [ug_m3] Bin11: lg(C*) =  3.5',
    'Aerosol [ug_m3] Bin12: lg(C*) =  4.5',
    'Aerosol [ug_m3] Bin13: lg(C*) =  5.5',
    'Aerosol [ug_m3] Bin14: lg(C*) =  6.5']
log_trans_cols: [ 'Precursor [ug/m3]' ]
tendency_cols: [ ]
model_configurations:
  MLP:
    DNN_1:
      hidden_layers: 1
      hidden_neurons: 500
      activation: "leaky"
      output_layers: 1
      output_activation: "linear"
      optimizer: "adam"
      loss: [ "mse" ]
      loss_weights: [ 1 ]
      lr: 0.0001
      batch_size: 2048
      use_noise: False
      noise_sd: 0.01
      epochs: 100
      use_dropout: False
      dropout_alpha: 0.1
      kernel_reg: 'l1_l2'
      l1_weight: 0.00001
      l2_weight: 0.0000001
      sgd_momentum: 0.9
      adam_beta_1: 0.9
      adam_beta_2: 0.999
      epsilon: 0.0000001
      decay: 0
      verbose: 1
      classifier: False