species: 'dodecane'
dir_path: '/glade/p/cisl/aiml/gecko/ML2019_dodecane_postproc/'
output_path: '/glade/work/cbecker/gecko-ml/applications/save_out/'
summary_file: 'C02000_Exp_List_ML2019_dodecane_v1_LatinHyperCube.csv'
aggregate_bins: True
save_models: True
ensemble_members: 1 # set to 1 for a single run
seq_length: 20 # only used with recurrent networks
scaler_type: "MinMaxScaler"
bin_prefix: ['Gas [ug/m3]', 'Aerosol [ug_m3]']
min_exp: 0
max_exp: 1999
num_exps: 200
input_vars: [
    'Time [s]',
    'Precursor [ug/m3]',
    'Gas [ug/m3]',
    'Aerosol [ug_m3]',
    'temperature (K)',
    'solar zenith angle (degree)',
    'pre-existing aerosols (ug/m3)',
    'o3 (ppb)',
    'nox (ppb)',
    'oh (10^6 molec/cm3)',
    'id']
output_vars: [
    'Time [s]',
    'Precursor [ug/m3]',
    'Gas [ug/m3]',
    'Aerosol [ug_m3]',
    'id']
model_configurations:
  single_ts_models:
    dnn_1:
      hidden_layers: 1
      hidden_neurons: 500
      activation: "leaky"
      output_layers: 3
      output_activation: "linear"
      optimizer: "adam"
      loss: ["mae", "mse", "mse"]
      loss_weights: [1, 20, 50]
      lr: 0.00005
      batch_size: 2048
      use_noise: False
      noise_sd: 0.01
      epochs: 30
      use_dropout: False
      dropout_alpha: 0.1
      l2_weight: 0.01
      sgd_momentum: 0.9
      adam_beta_1: 0.9
      adam_beta_2: 0.999
      decay: 0
      verbose:  1
      classifier: False


