species: 'toluene'
dir_path: '/glade/p/cisl/aiml/gecko/partition_data/'
# dir_path: 'AWS:ncar-aiml-data-commons/gecko/' #use prefix 'AWS:' if path is AWS bucket
output_path: '/home/cbecker/gecko_toluene_agg_runs'
aggregate_bins: True
ensemble_members: 1 # set to 1 for a single run
scaler_type: "StandardScaler"
bin_prefix: ['Gas [ug/m3]', 'Aerosol [ug_m3]']
box_val_exps: 'all'
random_seed: 8886
input_vars: [
    'Precursor [ug/m3]',
    'Gas [ug/m3]',
    'Aerosol [ug_m3]',
    'temperature (K)',
    'solar zenith angle (degree)',
    'pre-existing aerosols (ug/m3)',
    'o3 (ppb)',
    'nox (ppb)',
    'oh (10^6 molec/cm3)']
output_vars: [
    'Gas [ug/m3]',
    'Aerosol [ug_m3]']
log_trans_cols: ['Precursor [ug/m3]']
tendency_cols: []
model_configurations:
  MLP:
    DNN_1:
      hidden_layers: 1
      hidden_neurons: 500
      activation: "leaky"
      output_layers: 1
      output_activation: "linear"
      optimizer: "adam"
      loss: ["mse"]
      loss_weights: [1]
      lr: 0.0001
      batch_size: 2048
      use_noise: False
      noise_sd: 0.01
      epochs: 100
      use_dropout: False
      dropout_alpha: 0.1
      kernel_reg: 'l1_l2'
      l1_weight: 0.00001
      l2_weight: 0.0000001
      sgd_momentum: 0.9
      adam_beta_1: 0.9
      adam_beta_2: 0.999
      epsilon: 0.0000001
      decay: 0
      verbose:  1
      classifier: False
  
pbs:
  kernel: "ncar_pylib /glade/work/$USER/py37"
  bash: ["module load ncarenv/1.3 gnu/8.3.0 openmpi/3.1.4 python/3.7.5 cuda cudnn"]
  batch:
    N: "tolu-gru"
    l: ["select=1:ncpus=8:ngpus=1:mem=128GB", "walltime=12:00:00", "gpu_type=v100"]
    A: "NAML0001"
    q: "casper"
    o: "/glade/work/schreck/repos/GECKO_OPT/clean/gecko-ml/applications/test/out"
    e: "/glade/work/schreck/repos/GECKO_OPT/clean/gecko-ml/applications/test/err"
