log: 'results/100_no_tf'

data:
  data_path: "/glade/work/schreck/repos/gecko-ml/schreck/clustered/row_data"
  shuffle: True
  input_cols: [
    'Time [s]',
    'Precursor [ug/m3]',
    'Gas [ug/m3] Bin01: lg(C*) = -6.5',
    'Gas [ug/m3] Bin02: lg(C*) = -5.5',
    'Gas [ug/m3] Bin03: lg(C*) = -4.5',
    'Gas [ug/m3] Bin04: lg(C*) = -3.5',
    'Gas [ug/m3] Bin05: lg(C*) = -2.5',
    'Gas [ug/m3] Bin06: lg(C*) = -1.5',
    'Gas [ug/m3] Bin07: lg(C*) = -0.5',
    'Gas [ug/m3] Bin08: lg(C*) =  0.5',
    'Gas [ug/m3] Bin09: lg(C*) =  1.5',
    'Gas [ug/m3] Bin10: lg(C*) =  2.5',
    'Gas [ug/m3] Bin11: lg(C*) =  3.5',
    'Gas [ug/m3] Bin12: lg(C*) =  4.5',
    'Gas [ug/m3] Bin13: lg(C*) =  5.5',
    'Gas [ug/m3] Bin14: lg(C*) =  6.5',
    'Aerosol [ug_m3] Bin01: lg(C*) = -6.5',
    'Aerosol [ug_m3] Bin02: lg(C*) = -5.5',
    'Aerosol [ug_m3] Bin03: lg(C*) = -4.5',
    'Aerosol [ug_m3] Bin04: lg(C*) = -3.5',
    'Aerosol [ug_m3] Bin05: lg(C*) = -2.5',
    'Aerosol [ug_m3] Bin06: lg(C*) = -1.5',
    'Aerosol [ug_m3] Bin07: lg(C*) = -0.5',
    'Aerosol [ug_m3] Bin08: lg(C*) =  0.5',
    'Aerosol [ug_m3] Bin09: lg(C*) =  1.5',
    'Aerosol [ug_m3] Bin10: lg(C*) =  2.5',
    'Aerosol [ug_m3] Bin11: lg(C*) =  3.5',
    'Aerosol [ug_m3] Bin12: lg(C*) =  4.5',
    'Aerosol [ug_m3] Bin13: lg(C*) =  5.5',
    'Aerosol [ug_m3] Bin14: lg(C*) =  6.5',
    'temperature (K)',
    'solar zenith angle (degree)',
    'pre-existing aerosols (ug/m3)',
    'o3 (ppb)',
    'nox (ppb)',
    'oh (10^6 molec/cm3)',
    'id']
  output_cols: [
    'Time [s]',
    'Precursor [ug/m3]',
    'Gas [ug/m3] Bin01: lg(C*) = -6.5',
    'Gas [ug/m3] Bin02: lg(C*) = -5.5',
    'Gas [ug/m3] Bin03: lg(C*) = -4.5',
    'Gas [ug/m3] Bin04: lg(C*) = -3.5',
    'Gas [ug/m3] Bin05: lg(C*) = -2.5',
    'Gas [ug/m3] Bin06: lg(C*) = -1.5',
    'Gas [ug/m3] Bin07: lg(C*) = -0.5',
    'Gas [ug/m3] Bin08: lg(C*) =  0.5',
    'Gas [ug/m3] Bin09: lg(C*) =  1.5',
    'Gas [ug/m3] Bin10: lg(C*) =  2.5',
    'Gas [ug/m3] Bin11: lg(C*) =  3.5',
    'Gas [ug/m3] Bin12: lg(C*) =  4.5',
    'Gas [ug/m3] Bin13: lg(C*) =  5.5',
    'Gas [ug/m3] Bin14: lg(C*) =  6.5',
    'Aerosol [ug_m3] Bin01: lg(C*) = -6.5',
    'Aerosol [ug_m3] Bin02: lg(C*) = -5.5',
    'Aerosol [ug_m3] Bin03: lg(C*) = -4.5',
    'Aerosol [ug_m3] Bin04: lg(C*) = -3.5',
    'Aerosol [ug_m3] Bin05: lg(C*) = -2.5',
    'Aerosol [ug_m3] Bin06: lg(C*) = -1.5',
    'Aerosol [ug_m3] Bin07: lg(C*) = -0.5',
    'Aerosol [ug_m3] Bin08: lg(C*) =  0.5',
    'Aerosol [ug_m3] Bin09: lg(C*) =  1.5',
    'Aerosol [ug_m3] Bin10: lg(C*) =  2.5',
    'Aerosol [ug_m3] Bin11: lg(C*) =  3.5',
    'Aerosol [ug_m3] Bin12: lg(C*) =  4.5',
    'Aerosol [ug_m3] Bin13: lg(C*) =  5.5',
    'Aerosol [ug_m3] Bin14: lg(C*) =  6.5',
    'id']
  
iterator:
  num_workers: 4
  batch_size: 1024
  pin_memory: True
  shuffle: True

policy:
  state_dim: 35
  action_dim: 29
  max_action: 1.0
  actor_hidden_dims: [10000]
  actor_dropouts: [0.0]
  critic_hidden_dims: [10000, 1000]
  critic_dropouts: [0.0, 0.0]
  lr_actor: 0.0001
  lr_critic: 0.0001
  l2_actor: 0.0
  l2_critic: 0.0
  optimizer: "lookahead-diffgrad"
  discount: 0.1
  tau: 0.005
  
replay_buffer:
  state_dim: 35
  action_dim: 29
  min_size: 10000
  max_size: 1000000

trainer:
  start_epoch: 0
  epochs: 10000
  batch_size: 1024
  batches_per_epoch: 160
  experiment_batch_size: 1
  max_timestep: 100
  teacher_force: False
  gamma: 1.0
  clip: 1.0
  max_state: 1.0
  expl_noise: 0.01

callbacks:
  path_save: "results/100_no_tf"
  MetricsLogger:
    reload: False
  EarlyStopping:
    patience: 100
    verbose: True
    save_every_epoch: True
  ExponentialLR:
    gamma: 0.99
    
#   ReduceLROnPlateau: 
#     mode: "min"
#     factor: 0.2
#     patience: 1
#     min_lr: 0.0000000000000000001
#     verbose: True