name: GECKO-CI

on:
  [push]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          channel-priority: true
          auto-activate-base: false
          activate-environment: gecko
          environment-file: environment.yml
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Run pytest
        run: |
          conda activate gecko
          pytest
      - name: Run the gecko train script
        run: |
          conda activate gecko
          python applications/train_gecko_emulators.py -c config/ci_config.yml
      - name: Run the gecko box model script
        run: |
          conda activate gecko
          python applications/run_gecko_emulators.py -c config/ci_config.yml
